name: Add Event (Events & Appearances)
description: events.json にイベントを追加します
labels: ["event"]
body:
  - type: input
    id: title
    attributes:
      label: タイトル
      placeholder: 例) Avitation Vapor Office 跨年派對
    validations:
      required: true