name: Add Event (Events & Appearances)
description: events.json にイベントを追加します
labels: ["event"]

body:
  - type: dropdown
    id: type
    attributes:
      label: 種別
      options:
        - hosted
        - appearance
    validations:
      required: true

  - type: input
    id: title
    attributes:
      label: タイトル
      placeholder: 例) Avitation Vapor Office 跨年派對
    validations:
      required: true
